_target_: dataloader.demo_pair_loader.DemoPairLoader

root_path: /opt/data/private/SA2M/hydra-mesa/demo
scene_name: ""
image_name0: "4119.965344"
image_name1: "4120.813199"
color_folder: "color"
color_post: "png"
sem_folder: "samres"
sem_post: "npy"
intrin_folder: "intrins"
intrin_post: "txt"
